# Generated by Django 4.2 on 2023-04-16 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calorie", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="food",
            old_name="carbohydrates",
            new_name="fats",
        ),
    ]
